worker_processes  1;

events {
    worker_connections  1024;
}

http {
    inspect on;
    inspect_log /tmp/nginx-audit/logs/inspect.log;
    inspect_max_body_size 5m;
    inspect_buffer_size 64k;
    inspect_flush_time 100ms;
    inspect_log_per_worker on;

    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       18093;
        server_name  localhost;

        location / {
            root   html;
            index  index.html index.htm;
        }
    }
}
