worker_processes  1;
pid logs/nginx.pid;
error_log logs/error.log;

events {
    worker_connections  1024;
}

http {
    access_log logs/access.log;
    inspect on;
    inspect_log logs/inspect.log;
    inspect_max_body_size 1m;
    inspect_format tlv;
    inspect_dump on;
    inspect_dump_path dumps;
    inspect_dump_min_size 10;

    inspect_buffer_size 4k;
    inspect_flush_time 100ms;

    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # Backend for proxy tests
    upstream dev_backend {
        server 127.0.0.1:19100;
    }

    server {
        listen       19099;
        listen       19098;
        http2        on;
        server_name  localhost;

        location / {
            root   html;
            index  index.html;
        }

        location /proxy/ {
            proxy_pass         http://dev_backend/;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
        }
    }
}
